site_name: '${{values.app_name}}'
site_description: 'Main documentation for ${{values.app_name}}'
repo_url: https://github.com/minhpham95/${{values.app_name}}
edit_uri: edit/main/docs

plugins:
  - techdocs-core
  - redirects:
      redirect_maps:
        'index.md': 'docs/index.md'

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting Started: 'docs/index.md'
      - Architecture overview: 'docs/index.md'
      - Project Roadmap: 'docs/index.md'
      - Vision: 'docs/index.md'